name: "text_model"
platform: "onnxruntime_onnx"
max_batch_size: 32

input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [77]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [77]
  }
]

output [
  {
    name: "embedding"
    data_type: TYPE_FP32
    dims: [77, 512]
  }
]